### ISSUE TITLE
Los issues son tus mejores amigos

### ISSUE THREAD

**Issue by miguelpaz** [vanessacolon/vanessacolon.github.io#1]
Sirven para 

- [ ] To do list
- [ ] Decirle hola a los amigos
- [ ] Descansar
- [ ] Invitar a @laelectrique a que vea que hiciste tu sitio, etc

**Comment by vanessacolon** [comment]
Gracias.

**Comment by vanessacolon** [comment]
Reabro issue.

**Comment by vanessacolon** [comment]
Por hacer 
- [ ] ver [esto](http://gabelula.github.io/github-para-periodistas-presentacion/#/)
y
- [ ] ver [esto](https://miguelpaz.github.io/markdown-para-periodistas.html)
psssttt  @laelectrique y @maitehmateo
